openapi: 3.1.0

info:
  title: Game Vault API
  version: 1.0.0
  description: API for managing a personal video-game and console collection.

tags:
  - name: games
    description: API to manage the game library.

paths:
  /games:
    $ref: './endpoints/games.yaml'

  /games/{id}:
    $ref: './endpoints/games-id.yaml'
